resources:
  repositories:
    - repository: jhadrcSource
      type: github
      endpoint: Cloud-Web-Services
      name: Cloud-Web-Services/jhadrc-datacore-jh-edu
      ref: refs/heads/master
      #ref: $(Build.SourceBranch)
      trigger:
        batch: true
        branches:
          include:
          - release/*
          - main

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
- name: isScheduled
  value: $[eq(variables['Build.Reason'], 'Schedule')]

- group: jhadrc

stages:
- stage: source_check
  displayName: Source Check
  jobs:
  - job: source_check
    displayName: Source Check
    pool: $(pool)
    steps:
    - task: Bash@3
      displayName: 'Get Source Branch'
      inputs:
        targetType: 'inline'
        script: |
          echo "Source Branch: $(Build.SourceBranch)"
    - checkout: jhadrcSource
      path: jhadrcSource        
